-- 2. SELECIONE O NOME DOS FILMES E A DESCRIÇÃO DOS SEUS GÊNEROS, 
-- ORDENADOS PELO NOME DO FILME.

-- SELECT FILMES.NOME AS Nome_do_Filme, GENERO.DESCRICAO AS Descricao_do_Genero
-- FROM FILMES
-- JOIN GENERO ON FILMES.ID_GENERO = GENERO.ID
-- ORDER BY FILMES.NOME;

-- 3. SELECIONE O NOME DOS FILMES E A DESCRIÇÃO DOS SEUS GÊNEROS, 
-- ORDENADOS PELA DESCRIÇÃO DO GÊNERO.

-- SELECT FILMES.NOME AS Nome_do_Filme, GENERO.DESCRICAO AS Descricao_do_Genero
-- FROM FILMES
-- JOIN GENERO ON FILMES.ID_GENERO = GENERO.ID
-- ORDER BY GENERO.DESCRICAO

-- 4. SELECIONE O NOME DOS FILMES E A DESCRIÇÃO DOS SEUS GÊNEROS, 
-- ONDE O ID DO GÊNERO SEJA MAIOR QUE 3, ORDENADOS PELO NOME 
-- DO FILME.

-- SELECT FILMES.NOME AS Nome_do_Filme, GENERO.DESCRICAO AS Descricao_do_Genero
-- FROM FILMES
-- JOIN GENERO ON FILMES.ID_GENERO = GENERO.ID
-- WHERE GENERO.ID > 3
-- ORDER BY FILMES.NOME;

-- 5. SELECIONE O NOME DOS FILMES E A DESCRIÇÃO DOS SEUS GÊNEROS, 
-- ONDE O NOME DO FILME COMEÇA COM A LETRA 'A', ORDENADOS PELA 
-- DESCRIÇÃO DO GÊNERO.

-- SELECT FILMES.NOME AS Nome_do_Filme, GENERO.DESCRICAO AS Descricao_do_Genero
-- FROM FILMES
-- JOIN GENERO ON FILMES.ID_GENERO = GENERO.ID
-- WHERE FILMES.NOME LIKE 'A%'
-- ORDER BY GENERO.DESCRICAO;


-- 6. SELECIONE O NOME DOS FILMES E A DESCRIÇÃO DOS SEUS GÊNEROS, 
-- ONDE O NOME DO FILME CONTÉM A PALAVRA 'AMOR', ORDENADOS 
-- PELO NOME DO FILME

-- SELECT FILMES.NOME AS Nome_do_Filme, GENERO.DESCRICAO AS Descricao_do_Genero
-- FROM FILMES 
-- JOIN GENERO ON FILMES.ID_GENERO = GENERO.ID
-- WHERE FILMES.NOME LIKE '%AMOR%'
-- ORDER BY FILMES.NOME;

-- 7. SELECIONE O NOME DOS FILMES E A DESCRIÇÃO DOS SEUS GÊNEROS, 
-- ONDE O ID DO GÊNERO SEJA IGUAL A 2, ORDENADOS PELO NOME DO 
-- FILME

-- SELECT FILMES.NOME AS Nome_do_Filme, GENERO.DESCRICAO AS Descricao_do_Genero
-- FROM FILMES 
-- JOIN GENERO ON FILMES.ID_GENERO = GENERO.ID
-- WHERE GENERO.ID = 3
-- ORDER BY FILMES.NOME;

-- 8. SELECIONE O NOME DOS FILMES E A DESCRIÇÃO DOS SEUS GÊNEROS, 
-- ONDE A DESCRIÇÃO DO GÊNERO CONTÉM A PALAVRA 'DRAMA', 
-- ORDENADOS PELO ID DO FILME.

-- SELECT FILMES.NOME AS Nome_do_Filme, GENERO.DESCRICAO AS Descricao_do_Genero
-- FROM FILMES 
-- JOIN GENERO ON FILMES.ID_GENERO = GENERO.ID
-- WHERE GENERO.DESCRICAO LIKE '%DRAMA%'
-- ORDER BY FILMES.ID

-- 9. ATUALIZE O NOME DE UM FILME ESPECÍFICO (POR EXEMPLO, ID = 5) 
-- PARA 'NOVO NOME'.

-- UPDATE FILMES
-- SET NOME = 'VINGADORES A ERA DE ULTRON'
-- WHERE ID = 26;

-- 10. ATUALIZE O ID_GENERO DE UM FILME ESPECÍFICO (POR EXEMPLO, ID = 
-- 3) PARA 2.

-- UPDATE FILMES
-- SET ID_GENERO = 3
-- WHERE ID = 12;


